string process_filename
string camera_config_filename
string process_uid
bool db_cross_val_only
int64 image_display_time
bool cross_validate_in_execution
---
bool success
string results_dict
string results_path